// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_n2r68Jd2CXgqy7pBWB61XmfUdg06pM',
    appId: '1:707154603785:web:8f1cf3d01f4711482d6dd8',
    messagingSenderId: '707154603785',
    projectId: 'mainpro-5689b',
    authDomain: 'mainpro-5689b.firebaseapp.com',
    storageBucket: 'mainpro-5689b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnog-m8hKOD8ShscCwj8qFpv-2vemCuE',
    appId: '1:707154603785:android:c6941de74f8ca2e82d6dd8',
    messagingSenderId: '707154603785',
    projectId: 'mainpro-5689b',
    storageBucket: 'mainpro-5689b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwCXxVR7Wm3AZt9JRkPyRiliJTt7oTamg',
    appId: '1:707154603785:ios:5658ba30c1960d152d6dd8',
    messagingSenderId: '707154603785',
    projectId: 'mainpro-5689b',
    storageBucket: 'mainpro-5689b.firebasestorage.app',
    iosBundleId: 'com.example.velmoraApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwCXxVR7Wm3AZt9JRkPyRiliJTt7oTamg',
    appId: '1:707154603785:ios:5658ba30c1960d152d6dd8',
    messagingSenderId: '707154603785',
    projectId: 'mainpro-5689b',
    storageBucket: 'mainpro-5689b.firebasestorage.app',
    iosBundleId: 'com.example.velmoraApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE_n2r68Jd2CXgqy7pBWB61XmfUdg06pM',
    appId: '1:707154603785:web:0d7ae8da1bfadb092d6dd8',
    messagingSenderId: '707154603785',
    projectId: 'mainpro-5689b',
    authDomain: 'mainpro-5689b.firebaseapp.com',
    storageBucket: 'mainpro-5689b.firebasestorage.app',
  );
}
